### ISSUE TITLE
Printing Bins 

### ISSUE THREAD

**Issue by iwanttomakeapps** [benmaier/binpacking#10]
After running the little utility on a raspberry pi through command line it prints the bins, the sum of the weights in those bins but not which items were added to those bins to create those sums.

I see now that the bins are written as separate csv files in the directory where it runs. renamed as the bin number.

**Comment by benmaier** [comment]
that means I can close this, right?

**Comment by iwanttomakeapps** [comment]
It looks like in the code you had a note that says "print distributed items to bins with sizes" so that doesn't happen it just puts them in separate csv files instead of printing them

**Comment by benmaier** [comment]
The output says that the program did this: it put the items in the following bins, each with the given total containing weight. There's nothing saying that you should expect it to pre printed to the console.

**Comment by iwanttomakeapps** [comment]
Oh, would be cooler if it did. But yeah you can close it then thanks. Ill just glob the csvs and print that way cause im a noob at this.
