### ISSUE TITLE
Break down the dependency on numpy

### ISSUE THREAD

**Issue by bsergean** [benmaier/binpacking#11]
Hey there,

Thanks for this super helpful library. I'm trying to run this code in containers / cloud and the dependency on numpy gives me trouble. I browse through the code and could not find any crazy numerical algorithm, just convenience.

Do you think it's possible to just depend on straight python for this to work ?
(I'm only using this function for now -> to_constant_bin_number)

(I could do the work myself and maybe make a separate package, but if you like this idea maybe we can contribute this to this module).

Thanks !

**Comment by benmaier** [comment]
Hmm, that's an interesting remark. I'm not quite open to changing the requirements as I can't really estimate the size of the datasets that people use and wether changing it to pure Python might change anything in their workflow. On the other hand, there exist more efficient binpacking packages that people might use instead.

I'm open to a pull request in principle if you could provide some figures how the run time changes when the code is altered to rely on pure Python only. Alternatively, you might try to import numpy and when that fails with an `ImportError` one could fall back to the pure-Python version. That might be a more convenient and backwards-compatible solution. Unfortunately, I do not have time to work on that myself.

Cheers!

**Comment by bsergean** [comment]
Hey thanks for the feedback. That all make sense. I managed to simplify a bit the function I need to use now so that it doesn't use numpy. I don't think if I'll have time to contribute the solution you're proposing (the 'fallback' one) which is interesting.

Below is what I came up with, in a couple of hours which isn't brilliant but is all I need for now :) / I might post it as a gist or something somewhere.

There is no handling of list or tuple input data type (but that could be built 'outside), and there is no 'cleanup' of data (bad indices) like in your version.

I don't think that numpy makes too much of an impact on performance here, but I might be wrong. If you notice something buggy please let me know.

```
def findIndexOfSmallestValue(values):
    idx, _ = min(enumerate(values), key=operator.itemgetter(1))
    return idx


def to_constant_bin_number(d, N_bin):
    '''
    Distributes a dictionary of weights
    to a fixed number of bins while trying to keep the weight distribution constant.
    INPUT:
    --- d: dictionary where each (key,value)-pair carries the weight as value,
    '''

    items = [(val, key) for key, val in d.items()]
    items.sort()
    items.reverse()
    weights = [item[0] for item in items]
    keys = [item[1] for item in items]

    bins = [{} for i in range(N_bin)]

    # the total volume is the sum of all weights
    V_total = sum(weights)

    # the first estimate of the maximum bin volume is
    # the total volume divided to all bins
    V_bin_max = V_total / float(N_bin)

    # prepare array containing the current weight of the bins
    weight_sum = [0. for _ in range(N_bin)]

    # iterate through the weight list, starting with heaviest
    for i, weight in enumerate(weights):

        key = keys[i]

        # put next value in bin with lowest weight sum
        b = findIndexOfSmallestValue(weight_sum)
        # b = numpy.argmin(weight_sum)

        # calculate new weight of this bin
        new_weight_sum = weight_sum[b] + weight

        found_bin = False
        while not found_bin:

            # if this weight fits in the bin
            if new_weight_sum < V_bin_max:

                # ...put it in
                bins[b][key] = weight

                # increase weight sum of the bin and continue with
                # next item
                weight_sum[b] = new_weight_sum
                found_bin = True

            else:
                # if not, increase the max volume by the sum of
                # the rest of the bins per bin
                V_bin_max += sum(weights[i:]) / float(N_bin)

    return bins
```

**Comment by benmaier** [comment]
Great solution! Sorry I wasn't more helpful.

**Comment by bsergean** [comment]
No worries, you were extremely helpful in the first place by putting that library together. Removing a dependency isn't very hard.

Here's how I've been using binpacking lately, if you're interested -> https://bsergean.github.io/binpacking/

**Comment by benmaier** [comment]
nice! This is exactly the kind of application I had in mind when I wrote the package* :) good to see people are putting it to a good use!

*to be fair, it was the application I had in mind, but I pretty much only used it for distributing API calls to different keys, haha
