### ISSUE TITLE
debug print in to_constant_volume.py

### ISSUE THREAD

**Issue by pirovc** [benmaier/binpacking#13]
Hi @benmaier 

I guess you forgot this debug print in the new release ([v1.4.2](https://github.com/benmaier/binpacking/tree/v1.4.2)):
https://github.com/benmaier/binpacking/blob/3d7d7cbad3407aec9aa883268396890f9f53d2f9/binpacking/to_constant_volume.py#L57

Best
Vitor

**Comment by benmaier** [comment]
yikes. thanks for pointing that out. removed in 1.4.3.
