### ISSUE TITLE
Additional empty bin returned when all values exceed bin size

### ISSUE THREAD

**Issue by ovidiu-munteanu** [benmaier/binpacking#15]
When using `to_constant_volume` if all given values exceed the bin size, then an additional empty bin is returned.

Examples:

    # input 1
    values = [24, 42]
    bins = to_constant_volume(values, 20)
    
    # output 1
    bins = [[], [42], [24]]

    # input 2
    values = {"a": 24, "b": 42}
    bins = to_constant_volume(values, 20)
    
    # output 2
    bins = {{}, {"a": 42}, {"b": 24}}

**Comment by benmaier** [comment]
@ovidiu-munteanu thank you for finding and fixing this error!
