### ISSUE TITLE
Extra empty bin if all items can't fit into constant volume

### ISSUE THREAD

**Issue by bzamecnik** [benmaier/binpacking#17]
When I call `binpacking.to_constant_volume()` with input where all items are over bin_size there's an extra empty dict (bin) in the result.

```
binpacking.to_constant_volume({0: 5}, 3)                                                                                                  
[{}, {0: 5}]
# expected [{0: 5}]
>>> binpacking.to_constant_volume({0: 5, 1: 4}, 3)                                                                                            
[{}, {0: 5}, {1: 4}]
# expected [{0: 5}, {1: 4}]
```

When there's at least one item which fits, the extra bin disappears:

```
>>> binpacking.to_constant_volume({0: 5, 1: 3}, 3)                                                                                            
[{1: 3}, {0: 5}] # OK
```

Observed using the latest version 1.4.3.

---

It looks like in case of a single big item, we first initialize `bins = [ {} ]` with an empty bin, but then "f this weight doesn't fit in any existent bin" we append another empty bin `{}`. Likely on the latter place it should check if there isn't an existing initial empty bin and make a new one only if necessary.

**Comment by benmaier** [comment]
heya, thanks for pointing this out! I think this was just solved, I haven't had the time to update the version number and push to pypi yet: https://github.com/benmaier/binpacking/issues/15

**Comment by bzamecnik** [comment]
Aah, sorry. I checked only open issues but haven't noticed an unreleased fix and closed issue. Thanks!
