### ISSUE TITLE
Lambda key for lists

### ISSUE THREAD

**Issue by wontonst** [benmaier/binpacking#2]
It would be improve usability if we could pass in a lambda to retrieve the weight. The usage would be something like

```
a = [{'name': 'foo', 'weight': 30},
     {'name': 'bar', 'weight': 10}]
binpacking.to_constant_volume(a, key=lambda x: x['weight'], 30)
```

This would also eliminated the need for a weight_pos variable since it can then be written as

```
a = [('foo', 30), ('bar', 10)]
binpacking.to_constant_volume(a, key=lambda x: x[1], 30)
```

**Comment by benmaier** [comment]
sounds reasonable, can you do a PR?

**Comment by wontonst** [comment]
Sure, I'll add it to my backlog of stuff to do

**Comment by pgrooff** [comment]
When I try to install, I get the following message:
```
c:\temp\binpacking-1.3>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```
What to do?

**Comment by wontonst** [comment]
Thanks! @benmaier

**Comment by benmaier** [comment]
credit due @wjones1 :)
