### ISSUE TITLE
Varying size of bins

### ISSUE THREAD

**Issue by Prabin16** [benmaier/binpacking#21]
Is there a way we can use the package so  that we can optimize weights into various sizes of bins.

lets say I have infinite number of bins of following varying volume
bins = [10,20,30,40,48]
and following weights
weights = [10.5, 23.56, 6.5, 5.6, 6.75, 15.66, 0.59, 3.5, 40.1, 2.1, 17.15, 3.6, 2.56]

is there a way to get optimized array, which optimizes the weights in any bins.
the expected output will be something like this.
expected output = [[6.5, 3.5] [40.1, 6.75, 2.1], [23.56,17.15, 3.5, 3.6], [10.5, 5.6, 6.75, 15.66, 2.56]]

**Comment by benmaier** [comment]
not sure what you mean by optimized, but [the binpacking problem is NP-hard](https://en.wikipedia.org/wiki/Bin_packing_problem), so finding the true minimal number of necessary bins won't be possible generally. This package is less concerned with finding an optimal solution, but uses some heuristics to find a solution that is _fine_.

That set aside, was this package featured somewhere in a lecture or so? in the last days their was a sudden increase in activity here, which surprises me.

**Comment by Prabin16** [comment]
No, it not featured in lecture, at least for me.
I was learning python and came across a problem.
 Problem:
You have N lumbers with each varying length
You have of order of M pieces of wood where maximum lengthOf wood <= max length of lumber,

You have to optimize the cut so that the wood waste is minimum.
.
the binpacking was similar, and if the length of lumber is constant then it would work.
but I am still wondering around to find the algorithm that satisfies the condition above.

**Comment by benmaier** [comment]
Sounds fun, but you might want to ask this question in a forum that focuses on computer science in a broader sense. The discussions here should be limited to bugs and technicalities of this specific package.
