### ISSUE TITLE
Suggested contributions 

### ISSUE THREAD

**Issue by erelsgl** [benmaier/binpacking#26]
Hi, are you still working on this project?

I have some code for k-way number partitioning, as well as for some related problems such as bin-covering. Will you be interested in adding them?

**Comment by pedrocolodetti** [comment]
would you know how to tell me what type of greedy heuristics method this is?

**Comment by erelsgl** [comment]
Currently I have an exact algorithm that uses ILP: https://github.com/fuglede/numberpartitioning/pull/3

**Comment by erelsgl** [comment]
Here is the repository I started: https://github.com/erelsgl/prtpy
