### ISSUE TITLE
more than one weight

### ISSUE THREAD

**Issue by ka223** [benmaier/binpacking#29]
It would be very helpful if more than one weight could be sorted.
Would an option for two types of weights be possible?

**Comment by benmaier** [comment]
As this package is pretty much in maintenance mode, new features will probably not happen. 

In any case I'm also not quite sure I understand what you mean with "more than one weight", maybe you could compile a documented example case with input and expected output of such a function.

**Comment by ka223** [comment]
@benmaier 
Each bin has two types of weights` [x,y] `and each element also has two types `[x,y]`.

For example, a bin with `memory=8192`, `cpu=28`.
```
{'a': [512,16], 'b': [2048,8], 'c': [4096,8], 'd': [8192,28], 'e': [6144,16]}
[{'a': 512,16], 'c': [4096,8],} {'b': [2048,8],'e': [6144,16]}, {'d': [8192,28]}]
```

**Comment by benmaier** [comment]
hey, thanks! this will most likely not be implemented. at least not by me :) . Here's a few alternative packages, it might be that it's possible to do with those:

https://github.com/erelsgl/prtpy

https://pypi.org/project/binpacker/

https://github.com/solomon-b/greedypacker
