### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by benmaier** [benmaier/binpacking#3]
When I try to install, I get the following message:
```
c:\temp\binpacking-1.3>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```
What to do?

_Originally posted by @pgrooff in https://github.com/benmaier/binpacking/issues/2#issuecomment-453451063_

**Comment by benmaier** [comment]
@pgrooff it's probably to do with the change of some behavior when pip was updated to v10.0

I'll take a look at it later on

**Comment by benmaier** [comment]
installing with pip>=10.0 seems to work so I suspect the problem is on your system. Please try to install/update the package`setuptools` as described here

**Comment by pgrooff** [comment]
Thanks for the quick replies.
And yes I guess, the error comes from the fact that setuptools can not be found / not installed.

I know python, but I have never installed an external package.
All i did was  to copy your package to c:\temp and the cd c:\temp and python setyp.py install

**Comment by pgrooff** [comment]
I am still using python 2.7.14 on windows 10.

**Comment by benmaier** [comment]
I suggest to read a tutorial on Python's package manager 'pip'. maybe this one for starters https://packaging.python.org/tutorials/installing-packages/ . Also, you should update to Python 3.X because Python 2.7 will be discontinued within the next year. https://pythonclock.org/

**Comment by pgrooff** [comment]
Thanks for all the support.

**Comment by benmaier** [comment]
Can I close this issue?

**Comment by pgrooff** [comment]
Yes, sorry.
Thank you.

Regards, pim

Op za 2 mrt. 2019 11:05 schreef Benjamin F. Maier <notifications@github.com
