### ISSUE TITLE
Get keys when using binpacking.to_constant_volume(b,11)

### ISSUE THREAD

**Issue by ghost** [benmaier/binpacking#31]
Hello, 

Is there any way to get the keys names ( a, b, c ,d..) when using binpacking.to_constant_volume(b,11)

Thanks

**Comment by benmaier** [comment]
can you set up an example with code, including the behavior you observe and the behavior (input/output) you would expect?

**Comment by DogeVenci** [comment]
items = {a: 5, b:4, c:5, d:4, e:1, f:1}
binpacking.to_constant_volume(b,10)
would expect return [[a,b,e],[c,d,f]] but now return [[5,4,1],[5,4,1]]

**Comment by benmaier** [comment]
This is the output I get, i.e. with keys

```python
In [1]: import binpacking

In [2]: items = {'a': 5, 'b':4, 'c':5, 'd':4, 'e':1, 'f':1}
   ...: binpacking.to_constant_volume(items,10)
Out[2]: [{'a': 5, 'c': 5}, {'b': 4, 'd': 4, 'e': 1, 'f': 1}]
```

**Comment by benmaier** [comment]
Please check you're on version `1.5.1` or `1.5.2`. As I don't see any problem with the package I'll close this issue in a week if there's no further engagement.

**Comment by benmaier** [comment]
tuples work, too

```python
In [7]: items = list({'a': 5, 'b':4, 'c':5, 'd':4, 'e':1, 'f':1}.items())
   ...: print(f"{items=}")
   ...: binpacking.to_constant_volume(items,10,weight_pos=1)
items=[('a', 5), ('b', 4), ('c', 5), ('d', 4), ('e', 1), ('f', 1)]
Out[7]: [[('a', 5), ('c', 5)], [('b', 4), ('d', 4), ('e', 1), ('f', 1)]]
```
