### ISSUE TITLE
Why the inverse BFD heuristic?

### ISSUE THREAD

**Issue by YunHsiao** [benmaier/binpacking#4]
Hi there, 
Just stumbled upon this repo and played around for awhile, I noticed that when implementing `to_constant_volume`, the approach is to place each element into the most empty bin it fits into, basically the exact opposite of best-fit-decreasing heuristic:

https://github.com/benmaier/binpacking/blob/d9a7e8c8be2418b0c0a8cb82881e5eceb4286e09/binpacking/to_constant_volume.py#L95-L96

Is this just an accidental implementation bug or there's more theory backing this approach? Just being curious here :joy:

**Comment by benmaier** [comment]
Oof. thanks for pointing this out... I'll be looking into it soon!

**Comment by benmaier** [comment]
You closing this issue made me quickly look into the code: It seems to implement the BFD heuristic though? `np.argmin(weight_sum)` looks for the most empty bin (the one where total weight sum, i.e. "fill" is minimal) and if the weight does not fit it opens a new one. Am I missing something? Or is that why you closed the issue?

**Comment by YunHsiao** [comment]
Well it turns out that this is what's called 'worst-fit decreasing' heuristic. Don't get it wrong, it's still a valid heuristic but I don't see how this "aims at optimal distribution" since heuristics only provide approximations. Maybe you should consider implement something like bin completion or BCP?

Reference: [Schreiber 2013] Improved Bin Completion for Optimal Bin Packing and Number Partitioning

**Comment by YunHsiao** [comment]
For the record, BFD heuristic place each element into the most **full** bin it fits into, and vice versa for WFD.

**Comment by benmaier** [comment]
ah, now I see! thank you. Turns out I misinterpreted what best-fit means. Quite embarrassing! I'll fix it soon.

Also, I think I wrote "aims at" because that's the ultimate goal but of course it's not reached. Kinda misleading though, I agree.

**Comment by benmaier** [comment]
@YunHsiao would you be willing to check whether what I changed makes sense?

**Comment by YunHsiao** [comment]
Now it's proper BFD alright.
