### ISSUE TITLE
adding recipe to conda-forge

### ISSUE THREAD

**Issue by pirovc** [benmaier/binpacking#5]
Hello @benmaier ,

I'm adding this package to the conda-forge repository. I use your binpacking code in one of my tools [[TaxSBP](https://github.com/pirovc/taxsbp)] and I want to create a conda package for it. I'm also adding you as one of the recipe maintainers, if you agree please just say yes on this [PR](https://github.com/conda-forge/staged-recipes/pull/8086) (otherwise I remove your name, no worries). Thanks for the nice piece of code and recent update.

Vitor

**Comment by benmaier** [comment]
great! I have no idea how conda package management works but I'm eager to learn, so I'd be glad to be listed as a maintainer. Don't worry though, I won't blindly interfere. Cheers
